familyName: "Pitagon Sans Mono"
sources:
  - PitagonSansMono.glyphs
  - PitagonSansMono-Italic.glyphs
outputDir: "../fonts"
buildStatic: true
buildVariable: true
buildTTF: true
buildOTF: true
buildWebfont: true
